### ISSUE TITLE
Feature - Migrate components from corporate-ui v3.x

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#493]
**Is your feature request related to a problem? Please describe.**
Currently there are components in version 3.x that should be migrated into the new 4.x version of corporate-ui-dev 

**compare it to the current solution in 3.x**
What is missing(attributes)?
What have been added?
Should we remove it?

**Describe the solution you'd like**
A working component in version 4.x of corporate-ui

List: 

**c-corporate-header**
- [x] scania/corporate-ui-dev#93 Shortname
- [x] scania/corporate-ui-dev#124 Scania icon sticky nav
- [x] Responsive/mobile
- [x] scania/corporate-ui-dev#121 initial unit-test
- [x] scania/corporate-ui-dev#121 initial e2e test
- [ ] App/public/sm size (consider)
- [x] scania/corporate-ui-dev#116 Dealername

**c-main-navigation**
- [x] scania/corporate-ui-dev#142 text-decoration/hover effect on items
- [x] scania/corporate-ui-dev#122 Sticky nav
- [ ] Responsive/mobile
- [ ] scania/corporate-ui-dev#117 More solution
- [x] scania/corporate-ui-dev#121 initial unit-test
- [x] scania/corporate-ui-dev#121 initial e2e test

**c-corporate-footer**
- [x] scania/corporate-ui-dev#101 Remove drop
- [ ] Responsive/mobile
- [x] scania/corporate-ui-dev#121 initial unit-test
- [x] scania/corporate-ui-dev#121 initial e2e test

**Social-media**
- [ ] Responsive/mobile
- [x] scania/corporate-ui-dev#121 initial unit-test
- [x] scania/corporate-ui-dev#121 initial e2e test
- [x] scania/corporate-ui-dev#143 Remove or rename

 **fullscreen** (Will be added as a feature instead)
**main-hero** (consider)
**Login** (remade into a template instead)
**dashboard** (consider)
**Teaser** (consider)
**Alert** (Deprecated)
**Modal** (Deprecated)
**Map** (consider)
**Map-card** (consider)
