### ISSUE TITLE
Shipping List - Prod 4.0.0

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#522]
**Improvement:**
- [ ] #510 
- [x] #511 

**Bugs:**
- [x] scania/scania-theme#84
- [x] scania/scania-theme#100

 **Examples:**
- [x] scania/corporate-ui-angular#22
