### ISSUE TITLE
Shipping List - 4.0.1

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#527]
**Issues**
- [x] #506 
- [x] scania/corporate-ui-site#14
- [x] #510 

**PR**
- [x]  #526 
- [x] scania/scania-theme#113
- [x] scania/corporate-ui-site#28
- [x] scania/corporate-ui-site#29
