### ISSUE TITLE
Shipping List - 4.0.3

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#532]
- [ ] scania/corporate-ui-site#22
- [x] scania/scania-theme#118
- [ ] scania/scania-theme#116
- [ ] #505

**Comment by mmexvr** [comment]
outdated
